<!-- vin array object $SEND_TXVIN_ARRAYNUM start -->
                  <tr>
                    <th rowspan="4">$SEND_TXVIN_ARRAYNUM</th>
                    <th>txid</th>
                    <td class="text-break text-wrap">$SEND_TXVIN_TXID</td>
                  </tr>
                  <tr>
                    <th>vout</th>
                    <td>$SEND_TXVIN_VOUT</td>
                  </tr>
                  <tr>
                    <th>scriptSig</th>
                    <td class="text-break text-wrap">$SEND_TXVIN_SCRIPTSIG</td>
                  </tr>
                  <tr>
                    <th>sequenceid</th>
                    <td>$SEND_TXVIN_SEQID</td>
                  </tr>
                  <!-- vin array object $SEND_TXVIN_ARRAYNUM end -->