<!-- vout array object $SEND_TXVOUT_ARRAYNUM start -->
                  <tr>
                    <th rowspan="2">$SEND_TXVOUT_ARRAYNUM</th>
                    <th>value</th>
                    <td>$SEND_TXVOUT_VALUE</td>
                  </tr>
                  <tr>
                    <th>Address</th>
                    <td class="text-break text-wrap">$SEND_TXVOUT_ADDR</td>
                  </tr>
                  <!-- vout array object $SEND_TXVOUT_ARRAYNUM end -->