<!-- vin array object $TXIDINFO_TXVIN_ARRAYNUM start -->
                  <tr>
                    <th rowspan="5">$TXIDINFO_TXVIN_ARRAYNUM</th>
                    <th>txid</th>
                    <td class="text-break text-wrap">$TXIDINFO_TXVIN_TXID</td>
                  </tr>
                  <tr>
                    <th>vout</th>
                    <td>$TXIDINFO_TXVIN_VOUT</td>
                  </tr>
                  <tr>
                    <th>Amount</th>
                    <td>$TXIDINFO_TXVIN_AMOUNT $COIN</td>
                  </tr>
                  <tr>
                    <th>scriptSig</th>
                    <td class="text-break text-wrap">$TXIDINFO_TXVIN_SCRIPTSIG</td>
                  </tr>
                  <tr>
                    <th>sequenceid</th>
                    <td>$TXIDINFO_TXVIN_SEQID</td>
                  </tr>
                  <!-- vin array object $TXIDINFO_TXVIN_ARRAYNUM end -->