<!-- vout array object $TXIDINFO_TXVOUT_ARRAYNUM start -->
                  <tr>
                    <th rowspan="2">$TXIDINFO_TXVOUT_ARRAYNUM</th>
                    <th>value</th>
                    <td>$TXIDINFO_TXVOUT_VALUE</td>
                  </tr>
                  <tr>
                    <th>Address</th>
                    <td class="text-break text-wrap">$TXIDINFO_TXVOUT_ADDR</td>
                  </tr>
                  <!-- vout array object $TXIDINFO_TXVOUT_ARRAYNUM end -->