<tr>
                      <td>
                        $TXHIST_DIR_ARRAY
                      </td>
                      <td>$TXHIST_CONFIRMS</td>
                      <td>$TXHIST_AMOUNT</td>
                      <td>$TXHIST_HEIGHT</td>
                      <td class="text-break text-wrap"><a href="$URL/method/txidinfo?txid=$TXHIST_TXID&vout=$TXHIST_VOUT&height=$TXHIST_HEIGHT&nexturl=txidinfo">$TXHIST_TXID</a></td>
                    </tr>
