<tr>
                      <td>
                        $TXHIST_DIR_ARRAY
                      </td>
                      <td>$TXHIST_CONFIRMS</td>
                      <td>$TXHIST_AMOUNT</td>
                      <td>$TXHIST_HEIGHT</td>
                      <td>$TXHIST_TXID</td>
                      <td><button class="btn btn-primary btn-sm" formaction="$URL/method/txid?txid=$TXHIST_TXID&vout=1&nexturl=txidinfo" formmethod="get">Details</button></td>
                    </tr>