<tr>
                      <td>
                        <div class="row">
                          <div class="col-lg-2 col-sm-4 col-xs-12"><b>Type:</b><br>$MEMP_TYPE</div>
                          <div class="col-lg-4 col-sm-4 col-xs-12"><b>Dest. Address:</b><br>$MEMP_DEST</div>
                          <div class="col-lg-2 col-sm-4 col-xs-12"><b>Amount:</b><br>$MEMP_AMOUNT</div>
                          <div class="col-lg-4 col-sm-12 col-xs-12"><b>TxID:</b><br><span class="text-break text-wrap">$MEMP_TXID</span></div>
                        </div>
                      </td>
                    </tr>